apiVersion: v1
kind: ConfigMap
metadata:
  name: bootkey-config
  namespace: default
  labels:
    app: ethereum-poa
    name: bootkey-config
data:
  boot.key: |
    f96631980e56649dabeb40b6ae0b548f975bfa320a12fa89a36fa6207599f418
---
kind: Service
apiVersion: v1
metadata:
  name: ethereum-bootnode-svc
  namespace: default
  labels:
    app: ethereum-poa
    name: ethereum-bootnode-svc
spec:
  selector:
    app: ethereum-poa
    name: ethereum-bootnode-controller
  ports:
    - name: bootnode
      protocol: UDP
      port: 30301
      targetPort: 30301
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: ethereum-bootnode-controller
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ethereum-poa
        name: ethereum-bootnode-controller
    spec:
      containers:
      - name: ethereum-bootnode
        image: ethereum/client-go:alltools-v1.8.2
        command: ["bootnode"]
        args: ["--nodekey","/opt/bootnode/boot.key","--verbosity=9"]
        ports:
        - containerPort: 30301
          protocol: UDP
        volumeMounts:
        - name: bootkey-config-volume
          mountPath: /opt/bootnode/
      volumes:
      - name: bootkey-config-volume
        configMap:
          name: bootkey-config
          items:
          - key: boot.key
            path: boot.key
