---
kind: Service
apiVersion: v1
metadata:
  name: ethereum-node2-svc
  namespace: default
  labels:
    name: ethereum-node2-svc
spec:
  selector:
    name: ethereum-node2-deployment
  type: NodePort
  ports:
    - name: node2-jsonrpc
      protocol: TCP
      port: 8545
      targetPort: 8545
      nodePort: 30645
    - name: node2-tcp-ipc-discovery
      protocol: TCP
      port: 30303
      targetPort: 30303
    - name: node2-ipc-discovery
      protocol: UDP
      port: 30303
      targetPort: 30303
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ethereum-node2-deployment
  namespace: default
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      name: ethereum-node2-deployment
      labels:
        name: ethereum-node2-deployment
    spec:
      initContainers:
      - name: ethereum-node2-genesis-init
        image: ethereum/client-go:v1.8.2
        command: ["sh"]
        args: 
        - "-cx"
        - "if [ ! -d /root/.ethereum/password ]; then
            echo poaether-node2 > /root/.ethereum/password;
            echo 5b3dd1744bdc5e4737ae7e2a21b0cdcf393aa483 > /root/.ethereum/password_hash;
            mkdir /root/.ethereum/keystore;
            echo '{\"address\":\"5b3dd1744bdc5e4737ae7e2a21b0cdcf393aa483\",\"crypto\":{\"cipher\":\"aes-128-ctr\",\"ciphertext\":\"17f68860b2d07991a6d2ed43e2852698f5aab40b179dfb6cdcb4be038a3f684a\",\"cipherparams\":{\"iv\":\"4dc624bf2422a5988e357de80932f3db\"},\"kdf\":\"scrypt\",\"kdfparams\":{\"dklen\":32,\"n\":262144,\"p\":1,\"r\":8,\"salt\":\"0909d18063afe4847b666d9d94d2447a0b629975f9f917d1d516eb94b32b4b20\"},\"mac\":\"94647776e01dcf715ff94f7554257a1f05f97c9c92da14a077911af52cb7ba3b\"},\"id\":\"db673cfb-2003-45cd-9e95-26db5695b527\",\"version\":3}' > /root/.ethereum/keystore/UTC--2018-05-10T14-31-29.692629991Z--5b3dd1744bdc5e4737ae7e2a21b0cdcf393aa483;
            geth init /opt/genesis/genesis.json;
          fi;"
        ports:
        - containerPort: 8545
        - containerPort: 30303
        - containerPort: 30303
          protocol: UDP
        volumeMounts:
        - name: genesis-config-volume
          mountPath: /opt/genesis/
        - name: node2-persistent-storage
          mountPath: /root/.ethereum
      volumes:
      - name: genesis-config-volume
        configMap:
          name: genesis-config
          items:
          - key: genesis.json
            path: genesis.json
      - name: node2-persistent-storage
        hostPath:
          path: /var/lib/docker/geth-storage/node2
      containers:
      - name: ethereum-node2
        image: ethereum/client-go:v1.8.2
        command: ["sh"]
        args:
        - "-cx"
        - 'geth --bootnodes=enode://b616c6cf43c314268cf3e01378bf794220fed5ce2da77bbc8d9413c306fb9e680e514aaf5f18a5d5c428707e8a13fbd7a405b604a65c9ce51932b5e2125a9573@$(ETHEREUM_BOOTNODE_SVC_SERVICE_HOST):30301 --rpc --rpcaddr=0.0.0.0 --rpcapi=personal,db,eth,net,web3,txpool,miner --rpccorsdomain "*" --cache=512 --verbosity=4 --maxpeers=3 --syncmode "full" --networkid 1981 --gasprice 0 --unlock 0x5b3dd1744bdc5e4737ae7e2a21b0cdcf393aa483 --password /root/.ethereum/password --mine'
        ports:
        - containerPort: 8545
        - containerPort: 8546
        - containerPort: 30303
        - containerPort: 30303
          protocol: UDP
        - containerPort: 30304
          protocol: UDP
        volumeMounts:
        - name: genesis-config-volume
          mountPath: /opt/genesis/
        - name: node2-persistent-storage
          mountPath: /root/.ethereum
      volumes:
      - name: genesis-config-volume
        configMap:
          name: genesis-config
          items:
          - key: genesis.json
            path: genesis.json
      - name: node2-persistent-storage
        hostPath:
          path: /var/lib/docker/geth-storage/node2
