kind: Service
apiVersion: v1
metadata:
  name: ethereum-node2-svc
  namespace: default
  labels:
    name: ethereum-node2-svc
spec:
  selector:
    name: ethereum-node2-deployment
  ports:
    - name: node2-jsonrpc
      protocol: TCP
      port: 8545
      targetPort: 8545
    - name: node2-tcp-ipc-discovery
      protocol: TCP
      port: 30303
      targetPort: 30303
    - name: node2-ipc-discovery
      protocol: UDP
      port: 30303
      targetPort: 30303
